#!/usr/bin/env python3
# coding=utf-8
"""
MiniShellAgent Installation Script
Automatically detects the system and configures the shell environment
to enable direct use of the minishellagent command
"""

import os
import sys
import platform
import shutil
from pathlib import Path


class Colors:
    """Terminal colors"""
    RED = '\033[0;31m'
    GREEN = '\033[0;32m'
    YELLOW = '\033[1;33m'
    BLUE = '\033[0;34m'
    CYAN = '\033[0;36m'
    NC = '\033[0m'  # No Color


def print_info(msg):
    print(f"{Colors.BLUE}{msg}{Colors.NC}")


def print_success(msg):
    print(f"{Colors.GREEN}{msg}{Colors.NC}")


def print_warning(msg):
    print(f"{Colors.YELLOW}{msg}{Colors.NC}")


def print_error(msg):
    print(f"{Colors.RED}{msg}{Colors.NC}")


def detect_system():
    """Detect operating system type"""
    system = platform.system()
    if system == "Darwin":
        return "macOS"
    elif system == "Linux":
        return "Linux"
    elif system == "Windows":
        return "Windows"
    else:
        print_error(f"Unsupported system: {system}")
        sys.exit(1)


def detect_shell():
    """Detect default shell and configuration file"""
    system = platform.system()
    home = Path.home()
    
    if system == "Windows":
        # Windows: detect PowerShell or CMD
        # Check if PowerShell is available
        powershell_path = shutil.which("powershell.exe")
        
        if powershell_path:
            shell_name = "PowerShell"
            # PowerShell profile path (user-specific)
            # Try PowerShell 7+ profile first, then Windows PowerShell
            user_profile = os.environ.get('USERPROFILE', str(home))
            profile_path = Path(user_profile) / 'Documents' / 'PowerShell' / 'Profile.ps1'
            if not profile_path.exists():
                # Try Windows PowerShell 5.1 profile
                profile_path = Path(user_profile) / 'Documents' / 'WindowsPowerShell' / 'Profile.ps1'
            config_file = profile_path
        else:
            shell_name = "CMD"
            # For CMD, we'll use a batch file in user's home directory
            # Users can source this file or add it to their PATH
            config_file = home / '.minishellagent_env.bat'
    else:
        # Unix-like systems (macOS, Linux)
        shell = os.environ.get('SHELL', '/bin/zsh')
        shell_name = os.path.basename(shell)
        
        if shell_name == "zsh":
            config_file = home / ".zshrc"
        elif shell_name == "bash":
            config_file = home / ".bashrc"
            # macOS bash might use .bash_profile
            if system == "Darwin" and not config_file.exists():
                config_file = home / ".bash_profile"
        else:
            print_warning(f"Unrecognized shell: {shell_name}, will use zsh config")
            config_file = home / ".zshrc"
            shell_name = "zsh"
    
    return shell_name, config_file


def create_wrapper_script(project_dir, system_type):
    """Create an executable wrapper script for the current platform"""
    if system_type == "Windows":
        # Windows: use user's local bin directory or create one
        wrapper_dir = Path.home() / "AppData" / "Local" / "bin"
        wrapper_dir.mkdir(parents=True, exist_ok=True)
        wrapper_script = wrapper_dir / "minishellagent.bat"
        
        # Generate Windows batch script
        script_content = f'''@echo off
REM MiniShellAgent wrapper script
REM Generated by the installer

REM Resolve the project directory
if defined MINISHELLAGENT_HOME (
    set "PROJECT_DIR=%MINISHELLAGENT_HOME%"
) else (
    set "PROJECT_DIR={project_dir}"
)

REM Ensure the project directory exists
if not exist "%PROJECT_DIR%" (
    echo Error: MiniShellAgent project directory not found: %PROJECT_DIR%
    echo Please set MINISHELLAGENT_HOME environment variable
    exit /b 1
)

REM Save current working directory
set "MINISHELLAGENT_RUNTIME_CWD=%CD%"

REM Switch to project directory
cd /d "%PROJECT_DIR%"

REM Run the Python entry point
python -m minishellagent.main %*

REM Restore working directory
cd /d "%MINISHELLAGENT_RUNTIME_CWD%"
'''
    else:
        # Unix-like systems (macOS, Linux)
        wrapper_dir = Path.home() / ".local" / "bin"
        wrapper_dir.mkdir(parents=True, exist_ok=True)
        wrapper_script = wrapper_dir / "minishellagent"
        
        # Generate Unix shell script
        script_content = f'''#!/bin/bash
# MiniShellAgent wrapper script
# Generated by the installer

# Resolve the project directory
PROJECT_DIR="${{MINISHELLAGENT_HOME:-{project_dir}}}"

# Ensure the project directory exists
if [ ! -d "$PROJECT_DIR" ]; then
    echo "Error: MiniShellAgent project directory not found: $PROJECT_DIR"
    echo "Please set MINISHELLAGENT_HOME environment variable"
    exit 1
fi

# Save the user's current cwd to restore later
export MINISHELLAGENT_RUNTIME_CWD="$(pwd)"

# Switch to the project directory to load configs
cd "$PROJECT_DIR"

# Run the Python entry point (it will restore cwd)
python3 -m minishellagent.main "$@"
'''
    
    # Write the wrapper script to disk
    wrapper_script.write_text(script_content, encoding='utf-8')
    
    # Make the script executable (Unix-like only)
    if system_type != "Windows":
        os.chmod(wrapper_script, 0o755)
    
    print_success(f"Created wrapper script: {wrapper_script}")
    return wrapper_script, wrapper_dir


def update_shell_config(config_file, project_dir, wrapper_dir, system_type, shell_name):
    """Update shell configuration file to add PATH and environment variables"""
    # Ensure config file exists
    if not config_file.exists():
        print_warning(f"Config file does not exist, creating: {config_file}")
        config_file.parent.mkdir(parents=True, exist_ok=True)
        config_file.touch()
    
    # Read current content
    content = config_file.read_text(encoding='utf-8') if config_file.exists() else ""
    
    # Remove previous installation block
    lines = content.split('\n')
    new_lines = []
    skip = False
    
    for line in lines:
        if "# MiniShellAgent" in line or "REM MiniShellAgent" in line:
            skip = True
            continue
        if skip and (line.startswith("alias minishellagent") or 
                     ("PATH" in line and (".local/bin" in line or "AppData\\Local\\bin" in line)) or
                     "MINISHELLAGENT_HOME" in line or
                     line.strip().startswith("$env:Path") and "bin" in line):
            continue
        if skip and line.strip() == "":
            # Skip the first blank line after removal
            skip = False
            continue
        skip = False
        new_lines.append(line)
    
    # Append new configuration block
    new_lines.append("")
    
    if system_type == "Windows":
        if shell_name == "PowerShell":
            new_lines.append("# MiniShellAgent Configuration - Auto-generated by installer")
            new_lines.append(f'$env:MINISHELLAGENT_HOME = "{project_dir}"')
            # Add to PATH if not already present
            wrapper_dir_str = str(wrapper_dir).replace('\\', '\\\\')
            new_lines.append(f'if ($env:Path -notlike "*{wrapper_dir_str}*") {{')
            new_lines.append(f'    $env:Path += ";{wrapper_dir}"')
            new_lines.append('}')
        else:
            # CMD: use batch file approach
            new_lines.append("REM MiniShellAgent Configuration - Auto-generated by installer")
            new_lines.append(f'set "MINISHELLAGENT_HOME={project_dir}"')
            new_lines.append(f'set "PATH=%PATH%;{wrapper_dir}"')
    else:
        # Unix-like systems
        new_lines.append("# MiniShellAgent Configuration - Auto-generated by installer")
        new_lines.append(f'export MINISHELLAGENT_HOME="{project_dir}"')
        # Add to PATH if not already present
        wrapper_dir_str = str(wrapper_dir)
        if wrapper_dir_str not in os.environ.get('PATH', ''):
            new_lines.append(f'export PATH="$PATH:{wrapper_dir_str}"')
    
    # Write the modified configuration back to disk
    config_file.write_text('\n'.join(new_lines), encoding='utf-8')
    print_success(f"Updated configuration file: {config_file}")


def main():
    """Main installation flow"""
    print_info("=" * 50)
    print_info("MiniShellAgent Installation Script")
    print_info("=" * 50)
    print()
    
    # Detect operating system
    system = detect_system()
    print_success(f"Detected system: {system}")
    
    # Detect current shell
    shell_name, config_file = detect_shell()
    print_success(f"Detected shell: {shell_name}")
    print_success(f"Configuration file: {config_file}")
    
    # Determine project directory
    project_dir = Path(__file__).parent.absolute()
    print_info(f"Project directory: {project_dir}")
    print()
    
    # Verify Python installation
    python_cmd = shutil.which("python3") or shutil.which("python")
    if not python_cmd:
        print_error("Python not found. Please install Python 3 first.")
        sys.exit(1)
    print_success(f"Python path: {python_cmd}")
    print()
    
    # Create the wrapper script
    print_info("Creating wrapper script...")
    wrapper_script, wrapper_dir = create_wrapper_script(str(project_dir), system)
    print()
    
    # Update shell configuration file
    print_info("Updating shell configuration...")
    update_shell_config(config_file, str(project_dir), str(wrapper_dir), system, shell_name)
    
    # Finish the installer
    print()
    print_success("=" * 50)
    print_success("Installation completed!")
    print_success("=" * 50)
    print()
    print_info("Next steps:")
    
    if system == "Windows":
        if shell_name == "PowerShell":
            print("  1. Reload PowerShell profile:")
            print_warning(f"     . {config_file}")
            print()
            print("     Or restart PowerShell")
        else:
            print("  1. Restart your terminal or run:")
            print_warning(f"     {config_file}")
            print()
        print("  2. Then you can use:")
        print_warning("     minishellagent --help")
    else:
        print("  1. Reload shell configuration:")
        print_warning(f"     source {config_file}")
        print()
        print("  2. Then you can use:")
        print_warning("     minishellagent --help")
    
    print()
    print_info(f"Project directory: {project_dir}")
    print_info(f"Configuration file: {config_file}")
    print_info(f"Wrapper script: {wrapper_script}")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        print_warning("Installation cancelled")
        sys.exit(1)
    except Exception as e:
        print_error(f"Installation failed: {e}")
        import traceback
        traceback.print_exc()
        sys.exit(1)
